# Generated by Django 4.1.5 on 2023-02-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(choices=[('N', 'NOTURNO'), ('V', 'VESPERTINO'), ('M', 'MATUTINO')], default='M', max_length=1),
        ),
    ]
