# Generated by Django 4.1.5 on 2023-02-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_matricula_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(choices=[('N', 'NOTURNO'), ('M', 'MATUTINO'), ('V', 'VESPERTINO')], default='M', max_length=1),
        ),
    ]
